-- ============================================================
-- 01_schema.sql
-- 프로젝트 public 스키마 정의
-- ============================================================

CREATE EXTENSION IF NOT EXISTS postgis;


-- ============================================================
-- 1. 지도 기본 레이어
-- ============================================================

CREATE TABLE public.district_boundary (
    district_code VARCHAR(5) NOT NULL,
    district_name VARCHAR(50) NOT NULL,
    geom geometry(MultiPolygon, 5186) NOT NULL,
    CONSTRAINT district_boundary_pkey PRIMARY KEY (district_code)
);

CREATE INDEX idx_district_boundary_geom
    ON public.district_boundary USING GIST (geom);


CREATE TABLE public.traffic_incident (
    acc_id VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    expected_clear_at TIMESTAMP NULL,
    acc_type VARCHAR(10) NULL,
    acc_detail_type VARCHAR(20) NULL,
    link_id VARCHAR(20) NULL,
    acc_info TEXT NULL,
    geom geometry(Point, 5186) NOT NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT traffic_incident_pkey PRIMARY KEY (acc_id)
);

CREATE INDEX idx_traffic_incident_geom
    ON public.traffic_incident USING GIST (geom);


CREATE TABLE public.traffic_cctv (
    cctv_id VARCHAR(50) NOT NULL,
    cctv_name VARCHAR(200) NULL,
    center_name VARCHAR(200) NULL,
    xcoord DOUBLE PRECISION NOT NULL,
    ycoord DOUBLE PRECISION NOT NULL,
    movie_yn BOOLEAN NULL,
    geom geometry(Point, 5186) NOT NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT traffic_cctv_pkey PRIMARY KEY (cctv_id)
);

CREATE INDEX idx_traffic_cctv_geom
    ON public.traffic_cctv USING GIST (geom);


-- ============================================================
-- 2. 안전시설 레이어
-- ============================================================

CREATE TABLE public.crosswalk (
    crosswalk_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    management_no VARCHAR(100) NOT NULL,
    district_name VARCHAR(50) NULL,
    lot_address VARCHAR(255) NULL,
    crosswalk_type VARCHAR(100) NULL,
    raised_yn BOOLEAN NULL,
    pedestrian_signal_yn BOOLEAN NULL,
    acoustic_signal_yn BOOLEAN NULL,
    geom geometry(Point, 5186) NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT crosswalk_management_no_key UNIQUE (management_no),
    CONSTRAINT crosswalk_pkey PRIMARY KEY (crosswalk_id)
);

CREATE INDEX idx_crosswalk_geom
    ON public.crosswalk USING GIST (geom);


CREATE TABLE public.speed_hump (
    hump_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    management_no VARCHAR(100) NOT NULL,
    hump_type VARCHAR(3) NULL,
    installation_date DATE NULL,
    district_code VARCHAR(3) NULL,
    status VARCHAR(3) NULL,
    geom geometry(MultiPolygon, 5186) NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT speed_hump_management_no_key UNIQUE (management_no),
    CONSTRAINT speed_hump_pkey PRIMARY KEY (hump_id)
);

CREATE INDEX idx_speed_hump_geom
    ON public.speed_hump USING GIST (geom);


CREATE TABLE public.pedestrian_signal (
    signal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_sequence BIGINT NULL,
    district_name VARCHAR(50) NULL,
    address VARCHAR(255) NULL,
    management_no VARCHAR(100) NULL,
    signal_type VARCHAR(50) NULL,
    pedestrian_button_yn BOOLEAN NULL,
    acoustic_signal_yn BOOLEAN NULL,
    remaining_time_display_yn BOOLEAN NULL,
    geom geometry(Point, 5186) NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pedestrian_signal_pkey PRIMARY KEY (signal_id)
);

CREATE INDEX idx_pedestrian_signal_geom
    ON public.pedestrian_signal USING GIST (geom);


-- ============================================================
-- 3. 사용자 / 학교 / 사고다발지역
-- ============================================================

CREATE TABLE public.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_id VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    job_title VARCHAR(100) NULL,
    role VARCHAR(30) NOT NULL,
    organization VARCHAR(200) NULL,
    active_yn BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_login_id_key UNIQUE (login_id)
);


CREATE TABLE public.school (
    school_id VARCHAR(10) NOT NULL,
    school_name VARCHAR(200) NOT NULL,
    operation_status VARCHAR(20) NOT NULL,
    road_address VARCHAR(255) NULL,
    district_code VARCHAR(5) NULL,
    district_name VARCHAR(50) NULL,
    education_office_code VARCHAR(20) NULL,
    education_office_name VARCHAR(200) NULL,
    geom geometry(Point, 5186) NOT NULL,
    analysis_geom geometry(Polygon, 5186) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT school_pkey PRIMARY KEY (school_id)
);

CREATE INDEX idx_school_geom
    ON public.school USING GIST (geom);

CREATE INDEX idx_school_analysis_geom
    ON public.school USING GIST (analysis_geom);


CREATE TABLE public.accident_area (
    accident_area_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    afos_fid VARCHAR(22) NOT NULL,
    afos_id VARCHAR(20) NOT NULL,
    accident_type VARCHAR(30) NOT NULL,
    base_year SMALLINT NOT NULL,
    spot_cd VARCHAR(10) NOT NULL,
    spot_name VARCHAR(200) NOT NULL,
    accident_count INTEGER NOT NULL,
    casualty_count INTEGER NOT NULL,
    death_count INTEGER NOT NULL,
    serious_count INTEGER NOT NULL,
    minor_count INTEGER NOT NULL,
    reported_injury_count INTEGER NOT NULL,
    center_geom geometry(Point, 5186) NOT NULL,
    geom geometry(Polygon, 5186) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accident_area_pkey PRIMARY KEY (accident_area_id),
    CONSTRAINT accident_area_type_check CHECK (
        accident_type IN ('보행어린이', '어린이보호구역내 어린이')
    ),
    CONSTRAINT accident_area_source_key UNIQUE (accident_type, base_year, afos_fid)
);

CREATE INDEX idx_accident_area_center_geom
    ON public.accident_area USING GIST (center_geom);

CREATE INDEX idx_accident_area_geom
    ON public.accident_area USING GIST (geom);

CREATE INDEX idx_accident_area_year_type
    ON public.accident_area (base_year, accident_type);


-- ============================================================
-- 4. 점검 후보 / 점검 업무
-- ============================================================

CREATE TABLE public.inspection_candidate (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    school_id VARCHAR(10) NOT NULL,
    accident_area_id BIGINT NOT NULL,
    candidate_status VARCHAR(20) NOT NULL DEFAULT '미확인',
    exclusion_reason TEXT NULL,
    min_distance_m DOUBLE PRECISION NOT NULL,
    intersection_geom geometry(Geometry, 5186) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inspection_candidate_pkey PRIMARY KEY (candidate_id),
    CONSTRAINT inspection_candidate_school_fkey
        FOREIGN KEY (school_id) REFERENCES public.school (school_id),
    CONSTRAINT inspection_candidate_accident_area_fkey
        FOREIGN KEY (accident_area_id) REFERENCES public.accident_area (accident_area_id),
    CONSTRAINT inspection_candidate_school_accident_key
        UNIQUE (school_id, accident_area_id),
    CONSTRAINT inspection_candidate_status_check CHECK (
        candidate_status IN ('미확인', '선정', '검토제외')
    )
);

CREATE INDEX idx_inspection_candidate_intersection_geom
    ON public.inspection_candidate USING GIST (intersection_geom);

CREATE INDEX idx_inspection_candidate_school_id
    ON public.inspection_candidate (school_id);


CREATE TABLE public.inspection (
    inspection_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    school_id VARCHAR(10) NOT NULL,
    inspector_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    inspection_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT '점검예정',
    scheduled_date DATE NOT NULL,
    direct_reason TEXT NULL,
    inspection_date DATE NULL,
    inspection_content TEXT NULL,
    inspection_result TEXT NULL,
    improvement_required BOOLEAN NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inspection_pkey PRIMARY KEY (inspection_id),
    CONSTRAINT inspection_school_fkey
        FOREIGN KEY (school_id) REFERENCES public.school (school_id),
    CONSTRAINT inspection_inspector_fkey
        FOREIGN KEY (inspector_id) REFERENCES public.users (user_id),
    CONSTRAINT inspection_created_by_user_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES public.users (user_id),
    CONSTRAINT inspection_type_check CHECK (
        inspection_type IN ('후보 기반', '직접 등록')
    ),
    CONSTRAINT inspection_status_check CHECK (
        status IN ('점검예정', '점검완료')
    )
);

CREATE INDEX idx_inspection_school_id
    ON public.inspection (school_id);

CREATE INDEX idx_inspection_status
    ON public.inspection (status);

CREATE INDEX idx_inspection_inspector_id
    ON public.inspection (inspector_id);


CREATE TABLE public.inspection_candidate_link (
    inspection_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    CONSTRAINT inspection_candidate_link_pkey
        PRIMARY KEY (inspection_id, candidate_id),
    CONSTRAINT inspection_candidate_link_inspection_fkey
        FOREIGN KEY (inspection_id) REFERENCES public.inspection (inspection_id),
    CONSTRAINT inspection_candidate_link_candidate_fkey
        FOREIGN KEY (candidate_id) REFERENCES public.inspection_candidate (candidate_id)
);

CREATE INDEX idx_inspection_candidate_link_candidate_id
    ON public.inspection_candidate_link (candidate_id);


-- ============================================================
-- 5. 개선사항 / 후속조치
-- ============================================================

CREATE TABLE public.improvement (
    improvement_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inspection_id BIGINT NOT NULL,
    improvement_type VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    location_detail VARCHAR(255) NULL,
    action_status VARCHAR(20) NOT NULL DEFAULT '조치필요',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT improvement_pkey PRIMARY KEY (improvement_id),
    CONSTRAINT improvement_inspection_fkey
        FOREIGN KEY (inspection_id) REFERENCES public.inspection (inspection_id),
    CONSTRAINT improvement_action_status_check CHECK (
        action_status IN ('조치필요', '조치진행', '조치완료')
    )
);

CREATE INDEX idx_improvement_inspection_id
    ON public.improvement (inspection_id);

CREATE INDEX idx_improvement_action_status
    ON public.improvement (action_status);


CREATE TABLE public.follow_up_action (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    improvement_id BIGINT NOT NULL,
    manager_id BIGINT NOT NULL,
    action_date DATE NOT NULL,
    action_content TEXT NOT NULL,
    status_after VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT follow_up_action_pkey PRIMARY KEY (action_id),
    CONSTRAINT follow_up_action_improvement_fkey
        FOREIGN KEY (improvement_id) REFERENCES public.improvement (improvement_id),
    CONSTRAINT follow_up_action_manager_fkey
        FOREIGN KEY (manager_id) REFERENCES public.users (user_id),
    CONSTRAINT follow_up_action_status_after_check CHECK (
        status_after IN ('조치필요', '조치진행', '조치완료')
    )
);

CREATE INDEX idx_follow_up_action_improvement_id
    ON public.follow_up_action (improvement_id);

CREATE INDEX idx_follow_up_action_manager_id
    ON public.follow_up_action (manager_id);

CREATE INDEX idx_follow_up_action_action_date
    ON public.follow_up_action (action_date);


-- ============================================================
-- 6. 어린이보호구역 보조정보
-- ============================================================

CREATE TABLE public.school_zone (
    school_zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    school_id VARCHAR(10) NULL,
    facility_type VARCHAR(100) NULL,
    facility_name VARCHAR(200) NULL,
    road_address VARCHAR(255) NULL,
    lot_address VARCHAR(255) NULL,
    management_agency VARCHAR(200) NULL,
    police_station VARCHAR(200) NULL,
    cctv_installed_yn BOOLEAN NULL,
    cctv_count INTEGER NULL,
    road_width VARCHAR(100) NULL,
    data_reference_date DATE NULL,
    geom geometry(Point, 5186) NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT school_zone_pkey PRIMARY KEY (school_zone_id),
    CONSTRAINT school_zone_school_fkey
        FOREIGN KEY (school_id) REFERENCES public.school (school_id)
);

CREATE INDEX idx_school_zone_geom
    ON public.school_zone USING GIST (geom);

CREATE INDEX idx_school_zone_school_id
    ON public.school_zone (school_id);
