CREATE EXTENSION IF NOT EXISTS postgis;


-- public.crosswalk definition

-- Drop table

-- DROP TABLE public.crosswalk;

CREATE TABLE public.crosswalk (
	crosswalk_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	management_no varchar(100) NOT NULL,
	district_name varchar(50) NULL,
	lot_address varchar(255) NULL,
	crosswalk_type varchar(100) NULL,
	raised_yn bool NULL,
	pedestrian_signal_yn bool NULL,
	acoustic_signal_yn bool NULL,
	geom public.geometry(point, 5186) NULL,
	loaded_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT crosswalk_management_no_key UNIQUE (management_no),
	CONSTRAINT crosswalk_pkey PRIMARY KEY (crosswalk_id)
);
CREATE INDEX idx_crosswalk_geom ON public.crosswalk USING gist (geom);


-- public.speed_hump definition

-- Drop table

-- DROP TABLE public.speed_hump;

CREATE TABLE public.speed_hump (
	hump_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	management_no varchar(100) NOT NULL,
	hump_type varchar(3) NULL,
	installation_date date NULL,
	district_code varchar(3) NULL,
	status varchar(3) NULL,
	geom public.geometry(multipolygon, 5186) NULL,
	loaded_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT speed_hump_management_no_key UNIQUE (management_no),
	CONSTRAINT speed_hump_pkey PRIMARY KEY (hump_id)
);
CREATE INDEX idx_speed_hump_geom ON public.speed_hump USING gist (geom);


-- public.pedestrian_signal definition

-- Drop table

-- DROP TABLE public.pedestrian_signal;

CREATE TABLE public.pedestrian_signal (
	signal_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	source_sequence int8 NULL,
	district_name varchar(50) NULL,
	address varchar(255) NULL,
	management_no varchar(100) NULL,
	signal_type varchar(50) NULL,
	pedestrian_button_yn bool NULL,
	acoustic_signal_yn bool NULL,
	remaining_time_display_yn bool NULL,
	geom public.geometry(point, 5186) NOT NULL,
	loaded_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT pedestrian_signal_pkey PRIMARY KEY (signal_id)
);
CREATE INDEX idx_pedestrian_signal_geom ON public.pedestrian_signal USING gist (geom);